# Language Servers
[language-server.typos]
command = "typos-lsp"

[language-server.codebook]
command = "codebook-lsp"
args = ["server"]

[language-server.ruff]
command = "ruff"
args = ["server"]

# Example use in markdown:
[[language]]
name = "markdown"
language-servers = ["typos"]


#python config 

[[language]]
name = "python"
language-servers = ["ruff", "pylsp","typos"]

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = false
