theme = "bogster_light"

[editor]
true-color = true
# clipboard-provider = "termcode"
mouse = true
auto-format = true
auto-pairs = true
auto-completion = true

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
character = "â•Ž"
render = true

[keys.normal]
# The "Space" Leader setup
"space" = { "f" = "file_picker", "w" = ":w", "q" = ":q" }

# Navigation between Helix tabs (matches Zellij movement)
"A-h" = ":bp"
"A-l" = ":bn"
