theme = "bogster_light"

[editor]
true-color = true
# clipboard-provider = "termcode"
mouse = true
auto-format = true
auto-pairs = true
auto-completion = true

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
character = "â•Ž"
render = true
